Sprint 2
caspa2289/middle.messenger.praktikum.yandex pull request #2
Opened 2022-08-14 08:23 UTC by caspa2289

2022-08-14 15:37 UTC, podlovchenko requested changes
Привет)
Приложение не запускается
<img width="941" alt="Снимок экрана 2022-08-14 в 18 20 18" src="https://user-images.githubusercontent.com/22602747/184544334-95b3c662-892b-42af-8d70-13cba1e789b8.png">
Не хватает валидации по заданию
<img width="658" alt="Снимок экрана 2022-08-14 в 18 36 57" src="https://user-images.githubusercontent.com/22602747/184544366-c6bd1d3d-4f11-4cf6-a26b-0baf8d08ac51.png">

2022-08-14 15:37 UTC, podlovchenko commented on .gitignore
> +.github
В проекте во многих файлах есть ошибка EOF
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-08-14 15:37 UTC, podlovchenko commented on .stylelintcache
> +[{"/Users/19750648/Desktop/chatthing2/middle.messenger.praktikum.yandex/src/styles/common.scss":"1","/Users/19750648/Desktop/chatthing2/middle.messenger.praktikum.yandex/src/components/Form/Form.modu
Этого файла здесь не должно быть

2022-08-14 15:37 UTC, podlovchenko commented on server.ts
> +export {}
Из-за этого server не запускается

2022-08-14 15:37 UTC, podlovchenko commented on src/components/Button/Button.ts
> +class Button extends BaseComponent implements IButton {
Было бы здорово сделать класс Block [дженериком](https://www.typescriptlang.org/docs/handbook/2/generics.html), так будет возможность точно передать в базовый блок, тип пропсов наследников
Пример:
```
abstract class Block<Props extends {}> {
    private element: HTMLElement;
    private tagName: string;

    protected props: Props;

    public constructor(tagName: string = 'div', propsAndChildren: Props) {
        this.tagName = tagName;
        this.props = propsAndChildren;
    }
}

type ButtonProps = {
    onClick: () => {};
};

class Button extends Block<ButtonProps> {
    public constructor(props: ButtonProps) {
        super('div', props);
    }

    public onClick() {
        this.props.onClick();
    }
}
```

2022-08-14 15:37 UTC, podlovchenko commented on src/components/utility/BaseComponent/BaseComponent.ts
> +    __getReference() {
Для приватных полей не хватает модификатора private

2022-08-14 15:37 UTC, podlovchenko commented on src/components/utility/RequestSender/RequestSender.ts
> +const METHODS = {
enum обычно именуется в формате PascalCase

2022-08-14 15:37 UTC, podlovchenko commented on src/components/utility/RequestSender/RequestSender.ts
> +        | typeof METHODS.DELETE
```suggestion
    method?: Methods
```

2022-08-14 16:57 UTC, caspa2289 commented
> Привет) Приложение не запускается <img alt="Снимок экрана 2022-08-14 в 18 20 18" width="941" src="https://user-images.githubusercontent.com/22602747/184544334-95b3c662-892b-42af-8d70-13cba1e789b8.png"> Не хватает валидации по заданию <img alt="Снимок экрана 2022-08-14 в 18 36 57" width="658" src="https://user-images.githubusercontent.com/22602747/184544366-c6bd1d3d-4f11-4cf6-a26b-0baf8d08ac51.png">

Оно запускается, но ошибку я поправлю.

2022-08-14 17:24 UTC, caspa2289 commented on src/components/Button/Button.ts
> +class Button extends BaseComponent implements IButton {
Я эту конверсию в тс нашлёпал на обеде на работе, времени вообще не было в этом месяце. Доведу до ума в следующем спринте (не является публичной офертой).

2022-08-15 15:36 UTC, podlovchenko commented
Сейчас ошибка в tsconfig
Скорее всего из-за лишней запятой на 49 строке
<img width="1355" alt="Снимок экрана 2022-08-15 в 18 35 47" src="https://user-images.githubusercontent.com/22602747/184666709-623aa131-9a0e-43bb-adcd-ca0ff32836fb.png">

В валидации имени и фамилии не учитывается, что первая буква должна быть заглавной

2022-08-16 19:52 UTC, podlovchenko commented
Работу принимаю 👍

2022-08-25 07:38 UTC, merged